### ISSUE TITLE
wrong  when pip install corre_project

### ISSUE THREAD

**Issue by runtoforever** [tefantasy/WeightedCorrelationExtension#1]
I git clone this project from github. entering the project path when I run `pip` install ./  it get wrongs shown as below

`(base) wanglei@omnisky:/project/WeightedCorrelationExtension$ pip install ./
Processing /project/WeightedCorrelationExtension
Building wheels for collected packages: weighted-corr
  Building wheel for weighted-corr (setup.py) ... error
 ERROR: Command errored out with exit status 1:
   command: /home/wanglei/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-m3sz9uke/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-m3sz9uke/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-005d2105
       cwd: /tmp/pip-req-build-m3sz9uke/
  Complete output (313 lines):
  running bdist_wheel
  /home/wanglei/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py:352: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
    warnings.warn(msg.format('we could not find ninja.'))
  running build
  running build_ext
  building 'weighted_corr_cuda' extension
  creating build
  creating build/temp.linux-x86_64-3.8
  gcc -pthread -B /home/wanglei/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/wanglei/anaconda3/lib/python3.8/site-packages/torch/include -I/home/wanglei/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/wanglei/anaconda3/lib/python3.8/site-packages/torch/include/TH -I/home/wanglei/anaconda3/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/wanglei/anaconda3/include/python3.8 -c weighted_corr.cpp -o build/temp.linux-x86_64-3.8/weighted_corr.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=weighted_corr_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++` 

The Driver Version: 440.64.00    CUDA Version: 10.2 torch version: 1.7.1
Thank you advance.

**Comment by tefantasy** [comment]
Hi,

Thanks for noticing. 

Could you please downgrade your pytorch to any version between 1.3.0 and 1.6.0 and see if that works? I tried upgrading my pytorch to 1.7.1 and the installation failed as well... 

Here's my environment configuration for successful installation:
CUDA 10.1
torch 1.5.1 (also OK for 1.4.0, 1.6.0)
gcc 7.3.1

**Comment by runtoforever** [comment]
Thank.When I downgrade my pytorch to 1.5.0, it works.I am sorry that I hadn't noticed the version problem.

**Comment by tefantasy** [comment]
Good to hear that. The readme file has been updated.

**Comment by tefantasy** [comment]
@runtoforever Hi, I have also fixed the compilation error when using torch 1.7.1, and it should be working normally on that version. 

See [this issue](https://github.com/ClementPinard/Pytorch-Correlation-extension/issues/52).
